// <auto-generated />
namespace VSMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _3434kkasd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3434kkasd));
        
        string IMigrationMetadata.Id
        {
            get { return "201612280722045_3434kkasd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
